import { IShowsRepository, IAPIResponseShow } from '../adapters/IShowsRepository';

export class MockShowsRepository implements IShowsRepository {
  getShowsByQuery(query: string = 'girls'): Promise<IAPIResponseShow[]> {
    return Promise.resolve(this.createMockShows());
  }

  createMockShows(): IAPIResponseShow[] {
    return [
      {
        score: 0.9073471,
        show: {
          id: 139,
          url: 'https://www.tvmaze.com/shows/139/girls',
          name: 'Girls',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Romance'],
          status: 'Ended',
          runtime: 30,
          averageRuntime: 30,
          premiered: '2012-04-15',
          ended: '2017-04-16',
          officialSite: 'http://www.hbo.com/girls',
          schedule: { time: '22:00', days: ['Sunday'] },
          rating: { average: 6.6 },
          weight: 97,
          network: { id: 8, name: 'HBO', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 30124, thetvdb: 220411, imdb: 'tt1723816' },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/31/78286.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/31/78286.jpg',
          },
          summary: '<p>This Emmy winning series is a comic look at the assorted humiliations and rare triumphs of a group of girls in their 20s.</p>',
          updated: 1611310521,
          _links: { self: { href: 'https://api.tvmaze.com/shows/139' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/1079686' } },
        },
      },
      {
        score: 0.87689376,
        show: {
          id: 41734,
          url: 'https://www.tvmaze.com/shows/41734/girls',
          name: 'GIRLS',
          type: 'Scripted',
          language: 'Mongolian',
          genres: ['Comedy'],
          status: 'Ended',
          runtime: 41,
          averageRuntime: null,
          premiered: null,
          ended: null,
          officialSite: null,
          schedule: { time: '', days: ['Thursday'] },
          rating: { average: null },
          weight: 51,
          network: { id: 1672, name: 'UBS', country: { name: 'Mongolia', code: 'MN', timezone: 'Asia/Ulaanbaatar' } },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: null, thetvdb: null, imdb: 'tt8709752' },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/191/478539.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/191/478539.jpg',
          },
          summary: null,
          updated: 1632080861,
          _links: { self: { href: 'https://api.tvmaze.com/shows/41734' } },
        },
      },
      {
        score: 0.6998385,
        show: {
          id: 23542,
          url: 'https://www.tvmaze.com/shows/23542/good-girls',
          name: 'Good Girls',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Comedy', 'Crime'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2018-02-26',
          ended: '2021-07-22',
          officialSite: 'https://www.nbc.com/good-girls',
          schedule: { time: '21:00', days: ['Thursday'] },
          rating: { average: 7.3 },
          weight: 97,
          network: { id: 1, name: 'NBC', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: null, thetvdb: 328577, imdb: 'tt6474378' },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/297/744253.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/297/744253.jpg',
          },
          summary:
            '<p><b>Good Girls</b> follows three "good girl" suburban wives and mothers who suddenly find themselves in desperate circumstances and decide to stop playing it safe, and risk everything to take their power back.</p>',
          updated: 1627294164,
          _links: { self: { href: 'https://api.tvmaze.com/shows/23542' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/2108575' } },
        },
      },
      {
        score: 0.6994302,
        show: {
          id: 33320,
          url: 'https://www.tvmaze.com/shows/33320/derry-girls',
          name: 'Derry Girls',
          type: 'Scripted',
          language: 'English',
          genres: ['Comedy'],
          status: 'Running',
          runtime: 30,
          averageRuntime: 30,
          premiered: '2018-01-04',
          ended: null,
          officialSite: 'http://www.channel4.com/programmes/derry-girls',
          schedule: { time: '22:00', days: ['Tuesday'] },
          rating: { average: 8 },
          weight: 95,
          network: { id: 45, name: 'Channel 4', country: { name: 'United Kingdom', code: 'GB', timezone: 'Europe/London' } },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: null, thetvdb: 338903, imdb: 'tt7120662' },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/184/460240.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/184/460240.jpg',
          },
          summary:
            "<p>16-year-old Erin Quinn lives with her uncompromising mother, her long-suffering father and the fearsome ‘Granda Joe', a man whose love for his daughters and granddaughters is surpassed only by his contempt for his son-in-law.</p><p>It's the early 90s, and Erin is used to seeing her country on the nightly news and speaking in acronyms (The IRA, The UDA, The RUC). This is a time of armed police in armoured Land Rovers and British Army check points. But it's also the time of Murder She Wrote, The Cranberries, MJ and Lisa Marie, Doc Martens, bomber jackets, The X Files, Nirvana and Wayne's World. And while The Troubles may hang over her home town, Erin has troubles of her own</p>",
          updated: 1621933308,
          _links: { self: { href: 'https://api.tvmaze.com/shows/33320' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/1631064' } },
        },
      },
      {
        score: 0.69893134,
        show: {
          id: 525,
          url: 'https://www.tvmaze.com/shows/525/gilmore-girls',
          name: 'Gilmore Girls',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Comedy', 'Romance'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2000-10-05',
          ended: '2007-05-15',
          officialSite: null,
          schedule: { time: '21:00', days: ['Tuesday'] },
          rating: { average: 8.4 },
          weight: 95,
          network: { id: 5, name: 'The CW', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 3683, thetvdb: 76568, imdb: 'tt0238784' },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/4/11308.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/4/11308.jpg',
          },
          summary:
            '<p><b>Gilmore Girls</b> is a drama centering around the relationship between a thirtysomething single mother and her teen daughter living in Stars Hollow, Connecticut.</p>',
          updated: 1618158592,
          _links: { self: { href: 'https://api.tvmaze.com/shows/525' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/47639' } },
        },
      },
      {
        score: 0.69710517,
        show: {
          id: 42986,
          url: 'https://www.tvmaze.com/shows/42986/paper-girls',
          name: 'Paper Girls',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Science-Fiction'],
          status: 'In Development',
          runtime: null,
          averageRuntime: null,
          premiered: null,
          ended: null,
          officialSite: null,
          schedule: { time: '', days: [] },
          rating: { average: null },
          weight: 77,
          network: null,
          webChannel: { id: 3, name: 'Amazon Prime Video', country: null },
          dvdCountry: null,
          externals: { tvrage: null, thetvdb: 368187, imdb: 'tt10623646' },
          image: null,
          summary:
            '<p><b>Paper Girls </b>follows four young girls who, while out delivering papers on the morning after Halloween in 1988, become unwittingly caught in a conflict between warring factions of time-travelers, sending them on an adventure through time that will save the world. As they travel between our present, the past, and the future — they encounter future versions of themselves and now must choose to embrace or reject their fate. An emotional adventure in which the girls and the women they eventually become are tough, their friendships are authentic, and their journey through time is epic.</p>',
          updated: 1623788103,
          _links: { self: { href: 'https://api.tvmaze.com/shows/42986' } },
        },
      },
      {
        score: 0.69514346,
        show: {
          id: 27894,
          url: 'https://www.tvmaze.com/shows/27894/three-girls',
          name: 'Three Girls',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2017-05-16',
          ended: '2017-05-18',
          officialSite: 'http://www.bbc.co.uk/programmes/b08rgd5n',
          schedule: { time: '21:00', days: ['Tuesday', 'Wednesday', 'Thursday'] },
          rating: { average: 8.4 },
          weight: 47,
          network: { id: 12, name: 'BBC One', country: { name: 'United Kingdom', code: 'GB', timezone: 'Europe/London' } },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: null, thetvdb: 327999, imdb: 'tt6835252' },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/138/347202.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/138/347202.jpg',
          },
          summary:
            "<p><b>Three Girls</b> tells the true story of three of the children who were victims in the 2012 grooming and sex trafficking case in Rochdale.</p><p>Holly is new to Rochdale and keen to make friends and fit in. She finds herself drawn into a world she cannot escape, despite her pleas for help. It's a world that is all too familiar to sexual health worker Sara, who has been recording and reporting cases of child abuse for years.</p>",
          updated: 1513509678,
          _links: { self: { href: 'https://api.tvmaze.com/shows/27894' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/1164038' } },
        },
      },
      {
        score: 0.6946548,
        show: {
          id: 32087,
          url: 'https://www.tvmaze.com/shows/32087/chicken-girls',
          name: 'Chicken Girls',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Children', 'Music'],
          status: 'Running',
          runtime: null,
          averageRuntime: 14,
          premiered: '2017-09-05',
          ended: null,
          officialSite: 'https://www.youtube.com/playlist?list=PLVewHiZp3_LPhqzbcZFmS3iuDm9HymTsy',
          schedule: { time: '15:00', days: ['Tuesday'] },
          rating: { average: 5.7 },
          weight: 86,
          network: null,
          webChannel: { id: 274, name: 'Brat', country: { name: 'United States', code: 'US', timezone: 'America/New_York' } },
          dvdCountry: null,
          externals: { tvrage: null, thetvdb: 339854, imdb: null },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/355/888874.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/355/888874.jpg',
          },
          summary: '<p>Rhyme and her friends — known by their \'ship name, "The Chicken Girls" — have been dancing together forever. But this year, everything\'s changing...</p>',
          updated: 1636492374,
          _links: {
            self: { href: 'https://api.tvmaze.com/shows/32087' },
            previousepisode: { href: 'https://api.tvmaze.com/episodes/2203065' },
            nextepisode: { href: 'https://api.tvmaze.com/episodes/2203066' },
          },
        },
      },
      {
        score: 0.69334245,
        show: {
          id: 35096,
          url: 'https://www.tvmaze.com/shows/35096/girls-incarcerated',
          name: 'Girls Incarcerated',
          type: 'Documentary',
          language: 'English',
          genres: ['Crime'],
          status: 'To Be Determined',
          runtime: null,
          averageRuntime: 43,
          premiered: '2018-03-02',
          ended: null,
          officialSite: 'https://www.netflix.com/title/80185178',
          schedule: { time: '', days: [] },
          rating: { average: null },
          weight: 45,
          network: null,
          webChannel: { id: 1, name: 'Netflix', country: null },
          dvdCountry: null,
          externals: { tvrage: null, thetvdb: null, imdb: null },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/147/368834.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/147/368834.jpg',
          },
          summary:
            '<p>At Madison Juvenile Correctional Facility in Indiana, teen girls struggle with conflict and heartbreak as they try to turn their lives around. Fights, friendships, dating, rules. Teenage life is full of drama. But behind bars, the stakes are so much higher.</p>',
          updated: 1628178752,
          _links: { self: { href: 'https://api.tvmaze.com/shows/35096' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/1673379' } },
        },
      },
      {
        score: 0.6921824,
        show: {
          id: 1073,
          url: 'https://www.tvmaze.com/shows/1073/bomb-girls',
          name: 'Bomb Girls',
          type: 'Scripted',
          language: 'English',
          genres: ['Drama', 'Romance', 'War'],
          status: 'Ended',
          runtime: 60,
          averageRuntime: 60,
          premiered: '2012-01-04',
          ended: '2013-04-29',
          officialSite: null,
          schedule: { time: '20:00', days: ['Monday'] },
          rating: { average: 8.8 },
          weight: 47,
          network: { id: 67, name: 'Global', country: { name: 'Canada', code: 'CA', timezone: 'America/Halifax' } },
          webChannel: null,
          dvdCountry: null,
          externals: { tvrage: 30600, thetvdb: 254378, imdb: 'tt1955311' },
          image: {
            medium: 'https://static.tvmaze.com/uploads/images/medium_portrait/7/17549.jpg',
            original: 'https://static.tvmaze.com/uploads/images/original_untouched/7/17549.jpg',
          },
          summary:
            '<p>Set in the 1940s, <b>Bomb Girls</b> tells the remarkable stories of the women who risked their lives in a munitions factory building bombs for the Allied forces fighting on the European front. The series delves into the lives of these exceptional women – peers, friends and rivals – who find themselves thrust into new worlds and changed profoundly as they are liberated from their home and social restrictions.</p>',
          updated: 1592496010,
          _links: { self: { href: 'https://api.tvmaze.com/shows/1073' }, previousepisode: { href: 'https://api.tvmaze.com/episodes/108024' } },
        },
      },
    ]
  }
}

